/**
 * Full reference content for each of the 12 zodiac signs — written for the public,
 * crawlable /signos pages. Keeps the same voice as the rest of the product: astrology
 * as a lens for self-observation and action, never a deterministic promise.
 */
export type ZodiacSign = {
  slug: string;
  name: string;
  symbol: string;
  dateRange: string;
  element: "Fogo" | "Terra" | "Ar" | "Água";
  modality: "Cardinal" | "Fixo" | "Mutável";
  rulingPlanet: string;
  tagline: string;
  overview: string[];
  howTheyAct: string;
  love: string;
  career: string;
  growth: string;
  traits: string[];
  compatibleSigns: string[];
};

export const ZODIAC_SIGNS: readonly ZodiacSign[] = [
  {
    slug: "aries",
    name: "Áries",
    symbol: "♈",
    dateRange: "21 de março a 20 de abril",
    element: "Fogo",
    modality: "Cardinal",
    rulingPlanet: "Marte",
    tagline: "O primeiro passo, dado antes de pensar duas vezes.",
    overview: [
      "Áries abre o ciclo do zodíaco, e isso aparece em quase tudo: é o signo que começa, que decide primeiro, que não espera o cenário ficar perfeito para agir. Regido por Marte, carrega uma energia direta — quer resultado, não rodeio.",
      "A força de Áries é a iniciativa. Onde outros signos ainda estão avaliando prós e contras, o ariano já deu o primeiro passo. Essa pressa tem um preço: decisões tomadas rápido demais, sem checar o terreno, e uma tendência a perder o fôlego quando o projeto exige repetição em vez de arranque.",
    ],
    howTheyAct: "No dia a dia, Áries prefere resolver a discutir. Toma a frente em grupos, propõe primeiro e se irrita com processos lentos ou burocráticos. É competitivo consigo mesmo antes de ser com os outros — o que motiva o ariano é superar o que ele mesmo fez ontem.",
    love: "Nos relacionamentos, Áries é presente e direto: diz o que sente sem enrolar, e espera o mesmo de volta. Combina bem com parceiros que aguentam franqueza e não levam para o lado pessoal um jeito mais afiado de falar. O desafio é sustentar a atenção depois que a novidade passa — Áries se apaixona pela conquista, e precisa aprender a se apaixonar pela continuidade.",
    career: "No trabalho e nas finanças, Áries prospera quando pode iniciar projetos, não administrá-los para sempre. Tende a arriscar mais do que a média, o que tanto abre oportunidades quanto expõe a decisões impulsivas com dinheiro. O ponto de virada costuma ser aprender a manter um projeto depois da euforia inicial passar — é aí que a prosperidade realmente se constrói.",
    growth: "O maior aprendizado de Áries é a paciência com o próprio ritmo — nem tudo que vale a pena acontece rápido. Trabalhar a escuta antes da resposta, e a constância depois do impulso, é o que transforma energia em resultado duradouro.",
    traits: ["iniciativa", "coragem", "impulsividade", "competitividade", "franqueza", "energia"],
    compatibleSigns: ["Leão", "Sagitário", "Gêmeos", "Aquário"],
  },
  {
    slug: "touro",
    name: "Touro",
    symbol: "♉",
    dateRange: "21 de abril a 20 de maio",
    element: "Terra",
    modality: "Fixo",
    rulingPlanet: "Vênus",
    tagline: "Constância que constrói o que a pressa não consegue.",
    overview: [
      "Touro é o segundo signo do zodíaco e o primeiro de Terra — traz o impulso de Áries para o chão e pergunta: como isso se sustenta? Regido por Vênus, valoriza conforto, beleza e segurança material, e constrói tudo isso devagar, com os pés bem firmes.",
      "A palavra que define Touro é constância. É o signo que repete o pequeno hábito todos os dias até ele virar resultado grande — sem pressa, mas também sem parar. O contraponto dessa força é a resistência à mudança: uma vez que Touro se acomoda em uma rotina, sair dela custa caro, mesmo quando a rotina já não serve mais.",
    ],
    howTheyAct: "Touro pensa antes de agir e, uma vez decidido, é difícil demovê-lo. Prefere o caminho testado ao caminho novo, valoriza estabilidade acima de emoção, e costuma ser a pessoa mais confiável do grupo — quem cumpre o combinado mesmo quando ninguém está checando.",
    love: "No amor, Touro é leal e presente fisicamente: gestos de cuidado, tempo de qualidade e estabilidade pesam mais que grandes declarações. Precisa de segurança para se abrir, e pode demorar a confiar — mas quando confia, é para durar. O risco é confundir posse com cuidado, e travar a relação no medo de perder o que já tem.",
    career: "Financeiramente, Touro é o signo mais associado a construir patrimônio de forma sólida: guarda, planeja, evita risco desnecessário. Sua prosperidade vem de ritmo, não de sorte — metas pequenas e repetidas rendem mais para o taurino do que apostas grandes. O desafio é reconhecer quando é hora de atualizar um plano que já cumpriu seu propósito.",
    growth: "O aprendizado de Touro é soltar o controle sem soltar o cuidado — permitir mudança sem sentir que está perdendo o chão. Flexibilidade não é o oposto de estabilidade; é o que garante que ela dure.",
    traits: ["constância", "praticidade", "lealdade", "teimosia", "paciência", "sensorialidade"],
    compatibleSigns: ["Virgem", "Capricórnio", "Câncer", "Peixes"],
  },
  {
    slug: "gemeos",
    name: "Gêmeos",
    symbol: "♊",
    dateRange: "21 de maio a 20 de junho",
    element: "Ar",
    modality: "Mutável",
    rulingPlanet: "Mercúrio",
    tagline: "Curiosidade que conecta ideias antes de qualquer outro.",
    overview: [
      "Gêmeos é o primeiro signo de Ar e o mais mutável do trio inicial do zodíaco — vive de movimento, conversa e troca de ideias. Regido por Mercúrio, o planeta da comunicação, processa o mundo através da palavra, da leitura e da curiosidade constante.",
      "A marca de Gêmeos é a versatilidade: consegue conversar sobre quase qualquer assunto, se adapta rápido a contextos novos e nunca fica muito tempo preso a uma única ideia. Isso é uma força em ambientes que exigem agilidade, e um risco quando o projeto pede profundidade e permanência — Gêmeos se entedia fácil do que já entendeu.",
    ],
    howTheyAct: "No cotidiano, Gêmeos fala mais rápido do que decide, e decide mais rápido do que termina. Gosta de ter várias frentes abertas ao mesmo tempo, aprende testando e conversando, e costuma ser a pessoa que traz a informação nova para o grupo antes de qualquer outra.",
    love: "Nos relacionamentos, Gêmeos precisa de estímulo mental tanto quanto de afeto — parceiros que conversam bem e trazem assunto novo seguram sua atenção por mais tempo. Tende a evitar conflitos diretos, preferindo contornar com humor, o que pode deixar questões importantes sem resolução real.",
    career: "No trabalho e no dinheiro, Gêmeos se dá bem em funções que envolvem comunicação, vendas, conteúdo ou múltiplas tarefas simultâneas. A dispersão é o maior risco financeiro do signo: começar vários projetos e não terminar nenhum. Escolher uma ideia por vez, e ver ela até o fim, é o que transforma inteligência em prosperidade real.",
    growth: "O aprendizado de Gêmeos é a profundidade — ficar tempo suficiente em um assunto, uma pessoa ou um projeto para ir além da superfície. Nem toda curiosidade precisa virar uma nova direção.",
    traits: ["curiosidade", "comunicação", "adaptabilidade", "dispersão", "humor", "agilidade mental"],
    compatibleSigns: ["Libra", "Aquário", "Áries", "Leão"],
  },
  {
    slug: "cancer",
    name: "Câncer",
    symbol: "♋",
    dateRange: "21 de junho a 22 de julho",
    element: "Água",
    modality: "Cardinal",
    rulingPlanet: "Lua",
    tagline: "Memória e cuidado como formas de construir segurança.",
    overview: [
      "Câncer é o primeiro signo de Água e o que abre o segundo trimestre do zodíaco — depois do impulso, da construção e da comunicação, vem o cuidado. Regido pela Lua, é o signo mais ligado à emoção, à memória afetiva e à necessidade de pertencer a algum lugar.",
      "A força de Câncer é a intuição combinada com o cuidado prático: sente o clima de um ambiente antes de qualquer explicação lógica, e transforma esse sentimento em proteção — de si, da família, de quem confia nele. A sombra dessa mesma força é a insegurança: Câncer pode se fechar em uma concha quando sente que o ambiente não é seguro, mesmo quando a ameaça é só percepção.",
    ],
    howTheyAct: "No dia a dia, Câncer observa antes de agir, guarda detalhes que os outros esquecem e costuma ser quem lembra datas, preferências e histórico de quem está por perto. Tem um humor variável, ligado ao próprio ciclo emocional, e precisa de tempo sozinho para recarregar depois de ambientes muito expostos.",
    love: "No amor, Câncer é dos signos mais dedicados: cuida com ações concretas, cria rituais de casa e memória, e busca uma relação que pareça um porto seguro. O desafio é a dependência emocional e a dificuldade de sair de vínculos que já não fazem bem, por medo do que vem depois.",
    career: "Financeiramente, Câncer tende a guardar por segurança, não por ambição — dinheiro representa proteção para quem ama. Combina bem com negócios ligados a casa, alimentação, cuidado ou memória (como história, arquivo, produtos afetivos). O risco é deixar a insegurança comandar decisões financeiras por medo, em vez de planejamento.",
    growth: "O aprendizado de Câncer é confiar mesmo sem controlar tudo — abrir a concha antes de estar cem por cento seguro, porque a segurança plena nunca chega primeiro. Vem depois da confiança, não antes dela.",
    traits: ["intuição", "cuidado", "memória", "sensibilidade", "proteção", "lealdade familiar"],
    compatibleSigns: ["Escorpião", "Peixes", "Touro", "Virgem"],
  },
  {
    slug: "leao",
    name: "Leão",
    symbol: "♌",
    dateRange: "23 de julho a 22 de agosto",
    element: "Fogo",
    modality: "Fixo",
    rulingPlanet: "Sol",
    tagline: "Presença que quer ser vista fazendo algo que importa.",
    overview: [
      "Leão é o segundo signo de Fogo, e regido pelo próprio Sol — o centro do sistema. Isso aparece como necessidade genuína de brilhar, de ser reconhecido e de liderar pelo exemplo, não pela imposição. É um signo generoso quando se sente visto, e fechado quando se sente ignorado.",
      "A força de Leão é a presença: entra em uma sala e as pessoas notam, não por artifício, mas por uma confiança que costuma ser real. Essa mesma centralidade é o ponto de atenção — Leão pode confundir liderar com precisar de aprovação constante, e isso o torna vulnerável a validação externa em vez de critério próprio.",
    ],
    howTheyAct: "No cotidiano, Leão assume responsabilidade com naturalidade, gosta de organizar, apresentar e ser referência. É generoso com quem está ao redor, mas espera reconhecimento proporcional ao esforço — quando não recebe, o orgulho fala mais alto que a mágoa.",
    love: "No amor, Leão ama com intensidade e lealdade, e trata o parceiro como alguém a ser celebrado publicamente. Precisa de admiração recíproca — não vaidade vazia, mas reconhecimento genuíno do que constrói. O desafio é dividir o palco: aprender que a relação também precisa de espaço para o brilho do outro.",
    career: "Financeiramente, Leão investe onde pode liderar ou criar algo com a própria assinatura — negócio próprio, projeto autoral, posição de destaque. Gasta com generosidade, às vezes além do que planejou, para manter uma imagem de fartura. A prosperidade real vem quando aprende a construir por satisfação própria, não pela plateia.",
    growth: "O aprendizado de Leão é separar autoestima de aplauso — descobrir que o próprio critério vale mais do que a validação de quem está assistindo. Brilhar por escolha é mais sustentável do que brilhar por necessidade.",
    traits: ["criatividade", "liderança", "generosidade", "orgulho", "presença", "lealdade"],
    compatibleSigns: ["Áries", "Sagitário", "Gêmeos", "Libra"],
  },
  {
    slug: "virgem",
    name: "Virgem",
    symbol: "♍",
    dateRange: "23 de agosto a 22 de setembro",
    element: "Terra",
    modality: "Mutável",
    rulingPlanet: "Mercúrio",
    tagline: "Método que transforma detalhe em resultado confiável.",
    overview: [
      "Virgem é o segundo signo de Terra, e também regido por Mercúrio — mas onde Gêmeos usa a mente para conversar, Virgem usa a mesma mente para analisar, organizar e melhorar. É o signo mais associado a método, precisão e utilidade prática.",
      "A força de Virgem é a capacidade de ver o que precisa de ajuste antes de qualquer outra pessoa perceber. Essa atenção ao detalhe resolve problemas reais — mas, levada ao extremo, vira autocrítica severa e a sensação de que nada nunca está pronto o suficiente para ser entregue ou celebrado.",
    ],
    howTheyAct: "No dia a dia, Virgem organiza antes de agir, prefere sistemas confiáveis a improviso, e costuma ser quem nota o erro que ninguém mais viu. É útil de forma discreta, ajudando sem alarde, e se sente desconfortável recebendo elogio por algo que considera só ter feito direito.",
    love: "No amor, Virgem demonstra cuidado através de ações práticas — resolve, ajuda, cuida dos detalhes da vida do outro. Tem dificuldade de expressar sentimento em palavras grandes, e pode ser injustamente lido como frio quando na verdade está processando tudo internamente antes de mostrar.",
    career: "Financeiramente, Virgem é organizado, cuidadoso e avesso a risco desnecessário — controla gastos, planeja com antecedência e raramente é pego de surpresa. Se destaca em áreas que exigem precisão: análise, saúde, processos, qualidade. O risco é adiar decisões esperando uma certeza que nunca chega por completo.",
    growth: "O aprendizado de Virgem é aceitar o suficientemente bom — entregar, lançar, seguir em frente antes da perfeição impossível. Autocrítica é útil até o ponto em que impede a ação; depois disso, só trava.",
    traits: ["análise", "organização", "perfeccionismo", "praticidade", "discrição", "utilidade"],
    compatibleSigns: ["Touro", "Capricórnio", "Câncer", "Escorpião"],
  },
  {
    slug: "libra",
    name: "Libra",
    symbol: "♎",
    dateRange: "23 de setembro a 22 de outubro",
    element: "Ar",
    modality: "Cardinal",
    rulingPlanet: "Vênus",
    tagline: "Equilíbrio buscado através da relação com o outro.",
    overview: [
      "Libra é o segundo signo de Ar e abre o segundo semestre do zodíaco — depois do foco em si mesmo dos seis primeiros signos, Libra vira a atenção para o outro, para a parceria e para a busca de justiça e harmonia nas relações. Regido por Vênus, valoriza estética, equilíbrio e boa convivência.",
      "A força de Libra é a diplomacia: consegue ver múltiplos lados de uma situação e mediar conflitos com elegância. Essa mesma habilidade tem um custo — Libra pode demorar tanto para pesar os prós e contras que a decisão nunca sai do lugar, e pode priorizar a paz externa a ponto de abrir mão do que realmente quer.",
    ],
    howTheyAct: "No cotidiano, Libra busca consenso antes de impor opinião, se importa genuinamente com como o ambiente ao redor está, e tem talento natural para criar espaços agradáveis — visual, social ou emocionalmente. Evita confronto direto, preferindo negociar do que discutir.",
    love: "No amor, Libra floresce em parceria — é dos signos mais orientados para o relacionamento como projeto de vida. Busca equilíbrio, troca justa e beleza na relação. O desafio é a indecisão e a dificuldade de estar sozinho: Libra às vezes escolhe companhia errada só para não ficar sem nenhuma.",
    career: "Financeiramente, Libra se dá bem em parcerias de negócio, mediação, design ou qualquer área que exija equilíbrio entre partes. Tende a gastar com estética e conforto social, e pode adiar decisões financeiras importantes esperando a opção perfeita. Aprender a decidir com informação suficiente, sem esperar certeza total, é o que destrava a prosperidade.",
    growth: "O aprendizado de Libra é decidir sozinho quando for preciso — confiar no próprio critério sem precisar validar cada escolha com outra pessoa. Equilíbrio não significa nunca escolher um lado.",
    traits: ["diplomacia", "senso estético", "indecisão", "parceria", "justiça", "sociabilidade"],
    compatibleSigns: ["Gêmeos", "Aquário", "Leão", "Sagitário"],
  },
  {
    slug: "escorpiao",
    name: "Escorpião",
    symbol: "♏",
    dateRange: "23 de outubro a 21 de novembro",
    element: "Água",
    modality: "Fixo",
    rulingPlanet: "Plutão (e Marte, regente tradicional)",
    tagline: "Intensidade que não aceita nada superficial.",
    overview: [
      "Escorpião é o segundo signo de Água, e o mais intenso do zodíaco em praticamente qualquer classificação. Regido por Plutão — planeta da transformação profunda — não se contenta com a superfície de nada: quer entender o que está por trás, o que motiva de verdade, o que é real.",
      "A força de Escorpião é a capacidade de foco absoluto e de se reinventar depois de perdas que quebrariam outros signos. Essa intensidade, quando não tem para onde ir, vira controle — sobre si, sobre os outros, sobre situações que na verdade não podem ser controladas. Confiança é o bem mais raro que Escorpião oferece, e por isso mesmo o mais protegido.",
    ],
    howTheyAct: "No dia a dia, Escorpião observa mais do que fala, guarda informação como estratégia e raramente mostra as cartas antes da hora certa. Tem memória longa — tanto para lealdade quanto para mágoa — e prefere poucos vínculos profundos a muitos superficiais.",
    love: "No amor, Escorpião é intenso e exclusivo: quando se entrega, entrega tudo, e espera o mesmo nível de comprometimento de volta. Ciúme e necessidade de controle são o lado de sombra dessa intensidade. O crescimento vem quando aprende que confiança não é ingenuidade — é o que permite a intimidade que ele mesmo busca.",
    career: "Financeiramente, Escorpião é estratégico e capaz de se reinventar completamente quando um caminho se esgota — tem talento para investimentos de longo prazo e para áreas que exigem investigação, psicologia ou transformação. O risco é usar dinheiro como forma de controle, seja sobre si, seja sobre uma relação.",
    growth: "O aprendizado de Escorpião é soltar o controle sobre o que já não serve, sem precisar de uma crise para isso acontecer. A transformação que ele tanto busca nos outros começa sendo escolhida, não apenas sofrida.",
    traits: ["intensidade", "estratégia", "lealdade", "reserva", "capacidade de transformação", "ciúme"],
    compatibleSigns: ["Câncer", "Peixes", "Virgem", "Capricórnio"],
  },
  {
    slug: "sagitario",
    name: "Sagitário",
    symbol: "♐",
    dateRange: "22 de novembro a 21 de dezembro",
    element: "Fogo",
    modality: "Mutável",
    rulingPlanet: "Júpiter",
    tagline: "Expansão movida por sentido e liberdade.",
    overview: [
      "Sagitário é o terceiro e último signo de Fogo, regido por Júpiter — o planeta da expansão e da sorte. É o signo do horizonte: sempre olhando para o próximo destino, seja geográfico, intelectual ou espiritual. Otimismo natural e sede de significado definem quem é sagitariano.",
      "A força de Sagitário é a visão de longo prazo e a coragem de apostar no que ainda não existe. Essa mesma amplitude pode virar excesso: promessas grandes demais, planos que nunca saem do papel por falta de continuidade, e uma liberdade tão valorizada que compromissos parecem uma prisão.",
    ],
    howTheyAct: "No cotidiano, Sagitário fala com entusiasmo sobre o que está aprendendo ou planejando, evita rotinas muito fechadas e busca sentido em quase tudo que faz. É direto até parecer sem filtro, e prefere honestidade desconfortável a mentira gentil.",
    love: "No amor, Sagitário precisa de espaço e de um parceiro que também tenha vida própria — relação sufocante é o maior medo do signo. Quando encontra alguém que expande sua visão de mundo, em vez de limitá-la, o comprometimento vem naturalmente, sem perder a sensação de liberdade.",
    career: "Financeiramente, Sagitário pensa grande e otimista, às vezes otimista demais — subestima custos e prazos, e tem dificuldade com os detalhes operacionais de um plano ambicioso. Converter visão de futuro em compromissos pequenos e frequentes é o que transforma entusiasmo em prosperidade real, em vez de projeto que nunca sai do papel.",
    growth: "O aprendizado de Sagitário é a continuidade — terminar o que começou antes de já estar pensando no próximo horizonte. Liberdade e compromisso não são opostos quando o compromisso é escolhido, não imposto.",
    traits: ["otimismo", "visão de futuro", "honestidade", "independência", "entusiasmo", "inconstância"],
    compatibleSigns: ["Áries", "Leão", "Libra", "Aquário"],
  },
  {
    slug: "capricornio",
    name: "Capricórnio",
    symbol: "♑",
    dateRange: "22 de dezembro a 19 de janeiro",
    element: "Terra",
    modality: "Cardinal",
    rulingPlanet: "Saturno",
    tagline: "Disciplina que constrói o que dura décadas.",
    overview: [
      "Capricórnio é o terceiro signo de Terra e o mais orientado para longo prazo do zodíaco. Regido por Saturno — planeta da estrutura, do tempo e da responsabilidade —, encara qualquer objetivo como um projeto de anos, não de semanas, e tem a disciplina rara de sustentar esforço sem recompensa imediata.",
      "A força de Capricórnio é a estratégia combinada com trabalho consistente: sabe onde quer chegar e constrói o caminho degrau por degrau, mesmo quando ninguém está vendo. O peso dessa mesma força é a rigidez — consigo e com os outros — e uma cobrança interna que raramente reconhece o próprio progresso como suficiente.",
    ],
    howTheyAct: "No dia a dia, Capricórnio planeja antes de agir, valoriza reputação e resultado concreto acima de aparência, e prefere poucas palavras a muita conversa sem ação. Assume responsabilidade com naturalidade — às vezes responsabilidade demais, inclusive por coisas que não são só suas.",
    love: "No amor, Capricórnio demonstra cuidado através de compromisso prático e presença estável, mais do que romantismo declarado. Demora para se abrir, porque leva a sério o que constrói, mas quando se compromete é para o longo prazo. O desafio é deixar a vulnerabilidade aparecer antes de ter certeza absoluta de que é seguro.",
    career: "Financeiramente, Capricórnio é o signo mais naturalmente disposto a sacrificar prazer imediato por segurança futura — planeja, investe, sobe de posição com consistência. É também o signo mais propenso a se definir pelo próprio trabalho a ponto de esquecer o motivo original de tanto esforço.",
    growth: "O aprendizado de Capricórnio é comemorar o caminho, não só o topo — reconhecer cada etapa como parte legítima da conquista, em vez de adiar toda satisfação para um destino final que nunca chega por completo.",
    traits: ["disciplina", "estratégia", "responsabilidade", "ambição", "rigidez", "paciência"],
    compatibleSigns: ["Touro", "Virgem", "Escorpião", "Peixes"],
  },
  {
    slug: "aquario",
    name: "Aquário",
    symbol: "♒",
    dateRange: "20 de janeiro a 18 de fevereiro",
    element: "Ar",
    modality: "Fixo",
    rulingPlanet: "Urano (e Saturno, regente tradicional)",
    tagline: "Originalidade a serviço de algo maior que si mesmo.",
    overview: [
      "Aquário é o terceiro signo de Ar, regido por Urano — planeta da ruptura e da inovação. Pensa fora do padrão quase por reflexo, e tem verdadeiro desconforto com regras que existem só porque \"sempre foi assim\". É o signo mais ligado a causas coletivas e ao futuro.",
      "A força de Aquário é a capacidade de enxergar sistemas — como algo funciona, e como poderia funcionar melhor para mais gente, não só para si. Essa mente voltada ao coletivo pode custar proximidade individual: Aquário se conecta com a humanidade em geral às vezes com mais facilidade do que com a pessoa ao lado.",
    ],
    howTheyAct: "No cotidiano, Aquário questiona antes de aceitar, valoriza liberdade de pensamento acima de aprovação social, e costuma ter um círculo diverso de amizades unidas por ideia, não por proximidade física. Prefere lógica a drama emocional, o que pode ser lido como distância por quem espera mais afeto expresso.",
    love: "No amor, Aquário busca um parceiro que seja também amigo — alguém com quem trocar ideias, não só afeto. Tem dificuldade com demonstrações convencionais de romance e com rotina fechada demais. O crescimento vem ao permitir intimidade emocional sem tratá-la como perda de independência.",
    career: "Financeiramente, Aquário se destaca em áreas ligadas a tecnologia, inovação ou causas coletivas, e tende a ver dinheiro como ferramenta para viabilizar ideias, não como fim em si. O risco é o distanciamento de detalhes práticos — Aquário pensa no sistema todo e às vezes esquece o próprio orçamento no processo.",
    growth: "O aprendizado de Aquário é dar forma prática às ideias — sair do campo abstrato e aterrissar em ação concreta, sem perder a originalidade que é a maior força do signo.",
    traits: ["originalidade", "independência", "visão coletiva", "racionalidade", "distanciamento emocional", "inovação"],
    compatibleSigns: ["Gêmeos", "Libra", "Áries", "Sagitário"],
  },
  {
    slug: "peixes",
    name: "Peixes",
    symbol: "♓",
    dateRange: "19 de fevereiro a 20 de março",
    element: "Água",
    modality: "Mutável",
    rulingPlanet: "Netuno (e Júpiter, regente tradicional)",
    tagline: "Sensibilidade que sente antes de entender por quê.",
    overview: [
      "Peixes fecha o ciclo do zodíaco, e carrega um pouco da experiência de todos os onze signos anteriores — o que explica sua sensibilidade quase absorvente ao ambiente e às pessoas ao redor. Regido por Netuno, planeta da imaginação e da dissolução de limites, vive entre o mundo concreto e o mundo interno com a mesma naturalidade.",
      "A força de Peixes é a empatia e a imaginação: sente o que os outros sentem antes mesmo de qualquer palavra ser dita, e tem acesso fácil a criatividade, arte e intuição. O risco dessa mesma permeabilidade é a dificuldade de separar o que é seu do que é do outro — e de manter limites claros em relações e compromissos.",
    ],
    howTheyAct: "No dia a dia, Peixes absorve o clima emocional de qualquer ambiente, tem facilidade para se colocar no lugar do outro, e costuma precisar de tempo sozinho ou de expressão criativa para processar tanta informação sensível recebida. Evita confronto direto, preferindo se afastar a discutir.",
    love: "No amor, Peixes ama de forma quase incondicional, romântica e generosa — às vezes generosa demais, idealizando um parceiro além do que a realidade sustenta. O aprendizado é amar com os olhos abertos: ver a pessoa real, não só o potencial ou a versão idealizada dela.",
    career: "Financeiramente, Peixes tem dificuldade com estrutura rígida e planejamento de longo prazo — prefere fluir do que seguir planilha. Se destaca em áreas criativas, de cuidado ou espirituais, onde a sensibilidade é ativo, não obstáculo. Proteger a própria energia com limites práticos é o que evita que essa sensibilidade seja explorada financeiramente por outros.",
    growth: "O aprendizado de Peixes é o limite — saber onde termina o que é seu e começa o que é do outro, em sentimento, tempo e dinheiro. Sensibilidade sem proteção vira exaustão; com limite, vira dom.",
    traits: ["imaginação", "empatia", "sensibilidade", "idealização", "criatividade", "intuição"],
    compatibleSigns: ["Câncer", "Escorpião", "Touro", "Capricórnio"],
  },
];

export function getZodiacSign(slug: string): ZodiacSign | undefined {
  return ZODIAC_SIGNS.find((sign) => sign.slug === slug);
}
